export { GeneratorPage } from './Generator'
export { HistoryPage } from './History'
export { JobDetailPage } from './JobDetail'
export { ScheduledPage } from './Scheduled'
export { TestPage } from './Test'
